# Generated by Django 2.1.5 on 2019-01-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=50)),
                ('OBSID', models.CharField(max_length=50)),
                ('Observer', models.CharField(max_length=50)),
                ('Object', models.CharField(max_length=50)),
                ('RA', models.FloatField()),
                ('Decr', models.FloatField()),
                ('Exposure_time', models.FloatField()),
            ],
        ),
    ]
