# Generated by Django 2.1.5 on 2019-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iucaaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='UID',
            field=models.IntegerField(default=2018020606),
            preserve_default=False,
        ),
    ]
