# Generated by Django 2.1.5 on 2019-02-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iucaaapp', '0002_summary_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='Decr',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='Exposure_time',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='OBSID',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='Object',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='RA',
        ),
    ]
