# Generated by Django 2.1.5 on 2019-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iucaaapp', '0003_auto_20190226_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Observer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='summary',
            name='UID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='summary',
            name='folder',
            field=models.CharField(max_length=200),
        ),
    ]
