# Generated by Django 2.1.5 on 2019-02-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadA', models.CharField(max_length=200)),
                ('quadB', models.CharField(max_length=200)),
                ('quadC', models.CharField(max_length=200)),
                ('quadD', models.CharField(max_length=200)),
            ],
        ),
    ]
