# Generated by Django 2.1.5 on 2019-02-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0002_dph'),
    ]

    operations = [
        migrations.AddField(
            model_name='dph',
            name='UID',
            field=models.IntegerField(default=2018020606),
            preserve_default=False,
        ),
    ]
