# Generated by Django 2.1.5 on 2019-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0004_obsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsinfo',
            name='UID',
            field=models.IntegerField(default=2018020607),
            preserve_default=False,
        ),
    ]
