# Generated by Django 2.1.5 on 2019-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0005_obsinfo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqrstats',
            name='UID',
            field=models.IntegerField(default=2018020606),
            preserve_default=False,
        ),
    ]
