# Generated by Django 2.1.5 on 2019-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0006_dqrstats_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='housekeeping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('plot1', models.CharField(max_length=200)),
                ('plot2', models.CharField(max_length=200)),
                ('plot3', models.CharField(max_length=200)),
                ('plot4', models.CharField(max_length=200)),
                ('plot5', models.CharField(max_length=200)),
                ('plot6', models.CharField(max_length=200)),
                ('plot7', models.CharField(max_length=200)),
                ('plot8', models.CharField(max_length=200)),
                ('plot9', models.CharField(max_length=200)),
                ('plot10', models.CharField(max_length=200)),
                ('plot11', models.CharField(max_length=200)),
                ('plot12', models.CharField(max_length=200)),
                ('plot13', models.CharField(max_length=200)),
                ('plot14', models.CharField(max_length=200)),
            ],
        ),
    ]
