# Generated by Django 2.1.5 on 2019-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0007_housekeeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='countrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('crplot1', models.CharField(max_length=200)),
                ('crimg1', models.CharField(max_length=200)),
                ('crplot2', models.CharField(max_length=200)),
                ('crimg2', models.CharField(max_length=200)),
                ('crplot3', models.CharField(max_length=200)),
                ('crimg3', models.CharField(max_length=200)),
                ('crplot4', models.CharField(max_length=200)),
                ('crimg4', models.CharField(max_length=200)),
                ('crplot5', models.CharField(max_length=200)),
                ('crimg5', models.CharField(max_length=200)),
                ('crplot6', models.CharField(max_length=200)),
                ('crimg6', models.CharField(max_length=200)),
            ],
        ),
    ]
