# Generated by Django 2.1.5 on 2019-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0008_countrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='datainteg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('M9_A_BD', models.CharField(max_length=200)),
                ('M9_A_TP', models.CharField(max_length=200)),
                ('M9_A_DP', models.CharField(max_length=200)),
                ('M9_B_BD', models.CharField(max_length=200)),
                ('M9_B_TP', models.CharField(max_length=200)),
                ('M9_B_DP', models.CharField(max_length=200)),
                ('M9_C_BD', models.CharField(max_length=200)),
                ('M9_C_TP', models.CharField(max_length=200)),
                ('M9_C_DP', models.CharField(max_length=200)),
                ('M9_D_BD', models.CharField(max_length=200)),
                ('M9_D_TP', models.CharField(max_length=200)),
                ('M9_D_DP', models.CharField(max_length=200)),
                ('M0_A_BD', models.CharField(max_length=200)),
                ('M0_A_TP', models.CharField(max_length=200)),
                ('M0_A_DP', models.CharField(max_length=200)),
                ('M0_B_BD', models.CharField(max_length=200)),
                ('M0_B_TP', models.CharField(max_length=200)),
                ('M0_B_DP', models.CharField(max_length=200)),
                ('M0_C_BD', models.CharField(max_length=200)),
                ('M0_C_TP', models.CharField(max_length=200)),
                ('M0_C_DP', models.CharField(max_length=200)),
                ('M0_D_BD', models.CharField(max_length=200)),
                ('M0_D_TP', models.CharField(max_length=200)),
                ('M0_D_DP', models.CharField(max_length=200)),
                ('SS_A_BD', models.CharField(max_length=200)),
                ('SS_A_TP', models.CharField(max_length=200)),
                ('SS_A_DP', models.CharField(max_length=200)),
                ('SS_B_BD', models.CharField(max_length=200)),
                ('SS_B_TP', models.CharField(max_length=200)),
                ('SS_B_DP', models.CharField(max_length=200)),
                ('SS_C_BD', models.CharField(max_length=200)),
                ('SS_C_TP', models.CharField(max_length=200)),
                ('SS_C_DP', models.CharField(max_length=200)),
                ('SS_D_BD', models.CharField(max_length=200)),
                ('SS_D_TP', models.CharField(max_length=200)),
                ('SS_D_DP', models.CharField(max_length=200)),
            ],
        ),
    ]
