# Generated by Django 2.1.5 on 2019-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0009_datainteg'),
    ]

    operations = [
        migrations.CreateModel(
            name='datasat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=200)),
                ('QA_TS', models.CharField(max_length=200)),
                ('QA_SS', models.CharField(max_length=200)),
                ('QA_SP', models.CharField(max_length=200)),
                ('QB_TS', models.CharField(max_length=200)),
                ('QB_SS', models.CharField(max_length=200)),
                ('QB_SP', models.CharField(max_length=200)),
                ('QC_TS', models.CharField(max_length=200)),
                ('QC_SS', models.CharField(max_length=200)),
                ('QC_SP', models.CharField(max_length=200)),
                ('QD_TS', models.CharField(max_length=200)),
                ('QD_SS', models.CharField(max_length=200)),
                ('QD_SP', models.CharField(max_length=200)),
            ],
        ),
    ]
