# Generated by Django 2.1.5 on 2019-05-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0013_auto_20190530_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pixelprop',
        ),
    ]
