# Generated by Django 2.1.5 on 2019-05-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0014_delete_pixelprop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quadprop',
        ),
    ]
