# Generated by Django 2.1.5 on 2019-06-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0015_delete_quadprop'),
    ]

    operations = [
        migrations.CreateModel(
            name='pixelprop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=200)),
                ('PP_QA1_DID', models.CharField(max_length=200)),
                ('PP_QA1_PID', models.CharField(max_length=200)),
                ('PP_QA1_CNT', models.CharField(max_length=200)),
                ('PP_QA1_SG', models.CharField(max_length=200)),
                ('PP_QA2_DID', models.CharField(max_length=200)),
                ('PP_QA2_PID', models.CharField(max_length=200)),
                ('PP_QA2_CNT', models.CharField(max_length=200)),
                ('PP_QA2_SG', models.CharField(max_length=200)),
                ('PP_QA3_DID', models.CharField(max_length=200)),
                ('PP_QA3_PID', models.CharField(max_length=200)),
                ('PP_QA3_CNT', models.CharField(max_length=200)),
                ('PP_QA3_SG', models.CharField(max_length=200)),
            ],
        ),
    ]
