# Generated by Django 2.1.5 on 2019-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0016_pixelprop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB1_CNT',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB1_DID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB1_PID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB1_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB2_CNT',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB2_DID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB2_PID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB2_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB3_CNT',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB3_DID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB3_PID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelprop',
            name='PP_QB3_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
