# Generated by Django 2.1.5 on 2019-06-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0019_auto_20190602_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='quadprop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=200)),
                ('QP_QA1_MN', models.CharField(max_length=200)),
                ('QP_QA1_MD', models.CharField(max_length=200)),
                ('QP_QA1_SG', models.CharField(max_length=200)),
                ('QP_QA2_MN', models.CharField(max_length=200)),
                ('QP_QA2_MD', models.CharField(max_length=200)),
                ('QP_QA2_SG', models.CharField(max_length=200)),
                ('QP_QA3_MN', models.CharField(max_length=200)),
                ('QP_QA3_MD', models.CharField(max_length=200)),
                ('QP_QA3_SG', models.CharField(max_length=200)),
                ('QP_QB1_MN', models.CharField(max_length=200)),
                ('QP_QB1_MD', models.CharField(max_length=200)),
                ('QP_QB1_SG', models.CharField(max_length=200)),
                ('QP_QB2_MN', models.CharField(max_length=200)),
                ('QP_QB2_MD', models.CharField(max_length=200)),
                ('QP_QB2_SG', models.CharField(max_length=200)),
                ('QP_QB3_MN', models.CharField(max_length=200)),
                ('QP_QB3_MD', models.CharField(max_length=200)),
                ('QP_QB3_SG', models.CharField(max_length=200)),
            ],
        ),
    ]
