# Generated by Django 2.1.5 on 2019-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0020_quadprop'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC1_MD',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC1_MN',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC1_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC2_MD',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC2_MN',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC2_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC3_MD',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC3_MN',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QC3_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
