# Generated by Django 2.1.5 on 2019-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0021_auto_20190602_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD1_MD',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD1_MN',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD1_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD2_MD',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD2_MN',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD2_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD3_MD',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD3_MN',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprop',
            name='QP_QD3_SG',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
