# Generated by Django 2.1.5 on 2019-06-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0022_auto_20190602_0516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pixelprop',
        ),
    ]
