# Generated by Django 2.1.5 on 2019-06-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0023_delete_pixelprop'),
    ]

    operations = [
        migrations.CreateModel(
            name='pixelprop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=200)),
                ('PP_QA1_DID', models.CharField(max_length=200)),
                ('PP_QA1_PID', models.CharField(max_length=200)),
                ('PP_QA1_CNT', models.CharField(max_length=200)),
                ('PP_QA1_SG', models.CharField(max_length=200)),
                ('PP_QA2_DID', models.CharField(max_length=200)),
                ('PP_QA2_PID', models.CharField(max_length=200)),
                ('PP_QA2_CNT', models.CharField(max_length=200)),
                ('PP_QA2_SG', models.CharField(max_length=200)),
                ('PP_QA3_DID', models.CharField(max_length=200)),
                ('PP_QA3_PID', models.CharField(max_length=200)),
                ('PP_QA3_CNT', models.CharField(max_length=200)),
                ('PP_QA3_SG', models.CharField(max_length=200)),
                ('PP_QB1_DID', models.CharField(max_length=200)),
                ('PP_QB1_PID', models.CharField(max_length=200)),
                ('PP_QB1_CNT', models.CharField(max_length=200)),
                ('PP_QB1_SG', models.CharField(max_length=200)),
                ('PP_QB2_DID', models.CharField(max_length=200)),
                ('PP_QB2_PID', models.CharField(max_length=200)),
                ('PP_QB2_CNT', models.CharField(max_length=200)),
                ('PP_QB2_SG', models.CharField(max_length=200)),
                ('PP_QB3_DID', models.CharField(max_length=200)),
                ('PP_QB3_PID', models.CharField(max_length=200)),
                ('PP_QB3_CNT', models.CharField(max_length=200)),
                ('PP_QB3_SG', models.CharField(max_length=200)),
                ('PP_QC1_DID', models.CharField(max_length=200)),
                ('PP_QC1_PID', models.CharField(max_length=200)),
                ('PP_QC1_CNT', models.CharField(max_length=200)),
                ('PP_QC1_SG', models.CharField(max_length=200)),
                ('PP_QC2_DID', models.CharField(max_length=200)),
                ('PP_QC2_PID', models.CharField(max_length=200)),
                ('PP_QC2_CNT', models.CharField(max_length=200)),
                ('PP_QC2_SG', models.CharField(max_length=200)),
                ('PP_QC3_DID', models.CharField(max_length=200)),
                ('PP_QC3_PID', models.CharField(max_length=200)),
                ('PP_QC3_CNT', models.CharField(max_length=200)),
                ('PP_QC3_SG', models.CharField(max_length=200)),
                ('PP_QD1_DID', models.CharField(max_length=200)),
                ('PP_QD1_PID', models.CharField(max_length=200)),
                ('PP_QD1_CNT', models.CharField(max_length=200)),
                ('PP_QD1_SG', models.CharField(max_length=200)),
                ('PP_QD2_DID', models.CharField(max_length=200)),
                ('PP_QD2_PID', models.CharField(max_length=200)),
                ('PP_QD2_CNT', models.CharField(max_length=200)),
                ('PP_QD2_SG', models.CharField(max_length=200)),
                ('PP_QD3_DID', models.CharField(max_length=200)),
                ('PP_QD3_PID', models.CharField(max_length=200)),
                ('PP_QD3_CNT', models.CharField(max_length=200)),
                ('PP_QD3_SG', models.CharField(max_length=200)),
            ],
        ),
    ]
