# Generated by Django 2.1.5 on 2019-06-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0024_pixelprop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quadprop',
        ),
    ]
