# Generated by Django 2.1.5 on 2019-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0025_delete_quadprop'),
    ]

    operations = [
        migrations.CreateModel(
            name='quadprop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=200)),
                ('QP_QA1_MN', models.CharField(max_length=200)),
                ('QP_QA1_MD', models.CharField(max_length=200)),
                ('QP_QA1_SG', models.CharField(max_length=200)),
                ('QP_QA2_MN', models.CharField(max_length=200)),
                ('QP_QA2_MD', models.CharField(max_length=200)),
                ('QP_QA2_SG', models.CharField(max_length=200)),
                ('QP_QA3_MN', models.CharField(max_length=200)),
                ('QP_QA3_MD', models.CharField(max_length=200)),
                ('QP_QA3_SG', models.CharField(max_length=200)),
                ('QP_QB1_MN', models.CharField(max_length=200)),
                ('QP_QB1_MD', models.CharField(max_length=200)),
                ('QP_QB1_SG', models.CharField(max_length=200)),
                ('QP_QB2_MN', models.CharField(max_length=200)),
                ('QP_QB2_MD', models.CharField(max_length=200)),
                ('QP_QB2_SG', models.CharField(max_length=200)),
                ('QP_QB3_MN', models.CharField(max_length=200)),
                ('QP_QB3_MD', models.CharField(max_length=200)),
                ('QP_QB3_SG', models.CharField(max_length=200)),
                ('QP_QC1_MN', models.CharField(max_length=200)),
                ('QP_QC1_MD', models.CharField(max_length=200)),
                ('QP_QC1_SG', models.CharField(max_length=200)),
                ('QP_QC2_MN', models.CharField(max_length=200)),
                ('QP_QC2_MD', models.CharField(max_length=200)),
                ('QP_QC2_SG', models.CharField(max_length=200)),
                ('QP_QC3_MN', models.CharField(max_length=200)),
                ('QP_QC3_MD', models.CharField(max_length=200)),
                ('QP_QC3_SG', models.CharField(max_length=200)),
                ('QP_QD1_MN', models.CharField(max_length=200)),
                ('QP_QD1_MD', models.CharField(max_length=200)),
                ('QP_QD1_SG', models.CharField(max_length=200)),
                ('QP_QD2_MN', models.CharField(max_length=200)),
                ('QP_QD2_MD', models.CharField(max_length=200)),
                ('QP_QD2_SG', models.CharField(max_length=200)),
                ('QP_QD3_MN', models.CharField(max_length=200)),
                ('QP_QD3_MD', models.CharField(max_length=200)),
                ('QP_QD3_SG', models.CharField(max_length=200)),
            ],
        ),
    ]
