# Generated by Django 2.1.5 on 2019-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqrreport', '0026_quadprop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrate',
            name='UID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datainteg',
            name='UID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dph',
            name='UID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dqrstats',
            name='UID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='housekeeping',
            name='UID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='obsinfo',
            name='UID',
            field=models.CharField(max_length=200),
        ),
    ]
